### ISSUE TITLE
Run Failure

### ISSUE THREAD

**Issue by kiritigowda** [srohit0/trafficVision#2]
````
kiriti@simon:~/ISV/trafficVision$ ./main.py --video media/demo.mp4 
('Loaded', 'yoloOpenVX')
OK: loaded 22 kernels from libvx_nn.so
OK: OpenVX using GPU device#0 (gfx900) [OpenCL 1.2 ] [SvmCaps 0 1]
OK: annCreateInference: successful
Traceback (most recent call last):
  File "./main.py", line 49, in <module>
    yoloNet = inference.yoloInferenceNet(yoloOpenVX.weights);
  File "/home/kiriti/ISV/trafficVision/inference.py", line 28, in __init__
    input_info,output_info = yoloOpenVX.interface.annQueryInference().decode("utf-8").split(';')
ValueError: too many values to unpack

````

**Comment by kiritigowda** [comment]
@srohit0 can you check on this issue? Thanks!

**Comment by kiritigowda** [comment]
@srohit0 any update on this bug? I wanted to ingest this app into MIVisionX.

**Comment by srohit0** [comment]
@kiritigowda - will do it soon. 

I thought I already fixed it, will look at it again.

**Comment by srohit0** [comment]
Hello Kiriti, I updated mivisionX and ran the code again. Entire application seems to work. 

`
python> yoloOpenVX.interface.annQueryInference().decode("utf-8")
u'input,data,1,3,416,416;output,conv9,1,125,12,12'

python> input_info,output_info = yoloOpenVX.interface.annQueryInference().decode("utf-8").split(';')
`

I am trying to figure out mistake I may be making in reproducing the error you see. Do you have time to talk today?
