### ISSUE TITLE
why subtract 400 and 500?

### ISSUE THREAD

**Issue by feng1sun** [srohit0/trafficVision#7]
https://github.com/srohit0/trafficVision/blob/e58904218d26adfc7da47c9d7614e093f672308d/speedEstimator.py#L30

https://github.com/srohit0/trafficVision/blob/e58904218d26adfc7da47c9d7614e093f672308d/speedEstimator.py#L32

could you please explain why you subtract 400 and 500 in different directions? and how to get these values?

thank you very much.

**Comment by srohit0** [comment]
These numbers come from calibration of the picture frame to car speed. Center of bounding box speed calibration is simply a mapping of box-speed in pixels/sec to vehicle-speed in miles/hr (or km/hr if you happen to follow SI system).

Read more here: [Measuring Traffic Speed With Deep Learning Object Detection
](https://medium.com/datadriveninvestor/measuring-traffic-speed-with-deep-learning-object-detection-efc0bb9a3c57)
